[package]
name = "ptolemy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cbindgen = "0.24.5"

[build-dependencies]
cbindgen = "0.24.0"